apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
       - name: flaskcont
         image: praveen22233/flask:latest
         ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: flaskdemo
  ports:
  - port: 80
    targetPort: 5000
